# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cronin}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["S\305\202awosz S\305\202awi\305\204ski"]
  s.date = %q{2011-03-08}
  s.description = %q{Cronin can determine cron tasks executions}
  s.email = %q{slawosz@innov8on.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autospec",
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "cronin.gemspec",
    "lib/cronin.rb",
    "lib/cronin/abstract_timing.rb",
    "lib/cronin/cron_task.rb",
    "lib/cronin/hour.rb",
    "lib/cronin/hours.rb",
    "lib/cronin/minutes.rb",
    "lib/cronin/month_days.rb",
    "lib/cronin/months.rb",
    "lib/cronin/parser.rb",
    "lib/cronin/restricted.rb",
    "lib/cronin/week_days.rb",
    "spec/abstract_timing_spec.rb",
    "spec/cron_task_spec.rb",
    "spec/hour_spec.rb",
    "spec/hours_spec.rb",
    "spec/minutes_spec.rb",
    "spec/month_days_spec.rb",
    "spec/months_spec.rb",
    "spec/parser_spec.rb",
    "spec/restrictable_spec.rb",
    "spec/spec_helper.rb",
    "spec/week_days_spec.rb"
  ]
  s.homepage = %q{http://github.com/innov8on/cronin}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Cronin can determine cron tasks executions}
  s.test_files = [
    "spec/abstract_timing_spec.rb",
    "spec/cron_task_spec.rb",
    "spec/hour_spec.rb",
    "spec/hours_spec.rb",
    "spec/minutes_spec.rb",
    "spec/month_days_spec.rb",
    "spec/months_spec.rb",
    "spec/parser_spec.rb",
    "spec/restrictable_spec.rb",
    "spec/spec_helper.rb",
    "spec/week_days_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

